version: "3"

vars:
  ELASTICSEARCH_VERSION: "8.4.3"
  ELASTICSEARCH_IMAGE: "docker.elastic.co/elasticsearch/elasticsearch:{{.ELASTICSEARCH_VERSION}}"

tasks:
  pull:
    desc: Pull Elasticsearch Docker image
    cmds:
      - docker pull {{.ELASTICSEARCH_IMAGE}}

  run:
    desc: Run Elasticsearch container
    deps: [pull]
    cmds:
      - |
        docker run -it \
        --rm \
        --name elasticsearch \
        -m 4GB \
        -p 9200:9200 \
        -p 9300:9300 \
        -e "discovery.type=single-node" \
        -e "xpack.security.enabled=false" \
        docker.elastic.co/elasticsearch/elasticsearch:{{.ELASTICSEARCH_VERSION}}

  stop:
    desc: Stop Elasticsearch container
    cmds:
      - docker stop elasticsearch

  rm:
    desc: Remove Elasticsearch container
    deps: [stop]
    cmds:
      - docker rm elasticsearch

  check:
    desc: Ensure code quality
    cmds:
      - isort .
      - black .
